trigger:
- none

pool:
  vmImage: ubuntu-latest

steps:
- task: TerraformCLI@2
  inputs:
    command: 'init'
    backendType: 'azurerm'
    backendServiceArm: 'azlogin'
    allowTelemetryCollection: false
- task: Bash@3
  inputs:
    targetType: 'inline'
    script: 'echo "##vso[task.setvariable variable=workspace]$(cat environment_to_deploy.json|awk -F'': '' ''/env/{print $2}''|sed ''s/"//g'')"'

- task: TerraformCLI@2
  inputs:
    command: 'workspace'
    workspaceSubCommand: 'new'
    workspaceName: '$(workspace)'
    allowTelemetryCollection: false
    skipExistingWorkspace: true
- task: TerraformCLI@2
  inputs:
    command: 'workspace'
    allowTelemetryCollection: true
    workspaceName: '$(workspace)'
- task: TerraformCLI@2
  inputs:
    command: 'validate'
    allowTelemetryCollection: true
