trigger:
- none

pool:
  vmImage: ubuntu-latest

steps:
- task: TerraformCLI@2
  inputs:
    command: 'init'
    backendType: 'azurerm'
    backendServiceArm: 'azlogin'
    allowTelemetryCollection: false
    
- task: TerraformCLI@2
  inputs:
    command: 'validate'
    allowTelemetryCollection: true
